from pathlib import Path
text = Path('n8n/manifest/import_order.txt').read_text()
for name in [
    'wf_ingress_web_ui_master.json',
    'wf_ingress_telegram_master.json',
    'wf_connector_catalog.json',
    'wf_connector_registry_sync.json',
    'wf_connector_prepare.json',
    'wf_workflow_draft_generator.json',
    'wf_connector_smoke_test.json',
    'wf_connector_deployment_plan.json',
    'wf_connector_rollout_bundle.json',
    'wf_connector_persistence_report.json',
    'wf_connector_credential_matrix.json',
    'wf_auth_guard.json',
    'wf_idempotency_guard.json',
    'wf_admin_monitoring_dashboard.json',
    'wf_connector_health_monitor.json',
    'wf_retry_orchestrator_v2.json',
    'wf_queue_runtime_audit.json',
    'wf_connector_failure_isolation_audit.json',
    'wf_workflow_execution_cap_guard.json',
    'wf_ai_task_router.json',
    'wf_rag_document_ingest_governed.json',
    'wf_workflow_promotion_pipeline.json',
    'wf_workflow_version_history.json',
    'wf_workflow_version_rollback.json',
    'wf_release_manifest_build.json',
    'wf_release_checksum_validate.json',
    'wf_release_rollback_package.json',
    'wf_release_preflight_validation.json',
    'wf_release_publish_pipeline.json',
    'wf_release_publication_audit.json',
    'wf_release_channel_upsert.json',
    'wf_release_channel_plan.json',
    'wf_release_channel_execute.json',
    'wf_release_channel_execution_audit.json',
    'wf_data_lifecycle_audit.json',
    'wf_data_lifecycle_cleanup.json',
    'wf_tenant_membership_upsert.json',
    'wf_tenant_context_audit.json',
    'wf_tenant_policy_upsert.json',
    'wf_tenant_enforcement_audit.json',
    'wf_tenant_row_policy_upsert.json',
    'wf_tenant_row_isolation_audit.json',
    'wf_tenant_query_scope_audit.json',
    'wf_tenant_query_coverage_audit.json',
]:
    assert name in text, name
print('import order ok')
