from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
required = [
    'service/app/main.py',
    'service/app/connectors.py',
    'service/app/adapters/base.py',
    'docs/WORKLOG.md',
    'docs/generated_connector_workflow_manifest.json',
    'docs/generated_connector_readiness_report.json',
    'docs/generated_connector_deployment_plan.json',
    'docs/generated_connector_rollout_bundle.json',
    'docs/generated_connector_persistence_report.json',
    'docs/generated_connector_credential_matrix.json',
    'docs/generated_queue_runtime_report.json',
    'scripts/build_connector_failure_isolation_report.py',
    'docs/generated_connector_failure_isolation_report.json',
    'docs/generated_ai_control_report.json',
    'docs/generated_rag_governance_report.json',
    'docs/RESUME_FROM_HERE.md',
    'docs/IMPLEMENTATION_STATUS_MATRIX.md',
    'docs/PACKAGING_STATUS.md',
    'docs/CONNECTORS_AND_SERVICE_INTEGRATIONS.md',
    'docs/CREDENTIALS_AND_ENV_GUIDE.md',
    'docs/CODEX_WORKFLOW_AUTHORING_GUIDE.md',
    'docs/SMOKE_TEST_GUIDE.md',
    'docs/RELEASE_ENGINEERING_GUIDE.md',
    'docs/generated_release_manifest.json',
    'docs/generated_release_checksum_validation.json',
    'docs/generated_release_preflight_report.json',
    'docs/generated_release_publication_report.json',
    'docs/generated_release_channel_report.json',
    'docs/generated_release_channel_execution_report.json',
    'docs/generated_release_rollback_package.json',
    'artifacts/release_rollback_bundle_default.zip',
    'artifacts/release_publication_bundle_default.zip',
    'prompts/codex_connector_upgrade_prompt.md',
    'prompts/codex_generate_n8n_workflow_from_api_spec.md',
    'prompts/codex_continue_from_resume.md',
    'migrations/005_connector_runtime_and_smoke_tables.sql',
    'migrations/006_seed_connector_registry.sql',
    'migrations/007_enterprise_security_and_ops.sql',
    'migrations/008_workflow_version_events.sql',
    'migrations/009_queue_runtime_controls.sql',
    'migrations/010_ai_routing_and_rag_governance.sql',
    'migrations/011_failure_isolation_controls.sql',
    'migrations/012_release_engineering_controls.sql',
    'migrations/016_release_publication_automation.sql',
    'n8n/import/wf_connector_catalog.json',
    'n8n/import/wf_connector_prepare.json',
    'n8n/import/wf_connector_registry_sync.json',
    'n8n/import/wf_workflow_draft_generator.json',
    'n8n/import/wf_connector_smoke_test.json',
    'n8n/import/wf_connector_preflight_audit.json',
    'n8n/import/wf_connector_workflow_manifest.json',
    'n8n/import/wf_connector_readiness_report.json',
    'n8n/import/wf_connector_deployment_plan.json',
    'n8n/import/wf_connector_rollout_bundle.json',
    'n8n/import/wf_connector_persistence_report.json',
    'n8n/import/wf_connector_credential_matrix.json',
    'n8n/import/wf_pubmed_search.json',
    'n8n/import/wf_arxiv_search.json',
    'n8n/import/wf_google_drive_fetch.json',
    'n8n/import/wf_mlflow_run_lookup.json',
    'n8n/import/wf_azure_ml_job_lookup.json',
    'n8n/import/wf_figma_file_inspect.json',
    'n8n/import/wf_kaggle_dataset_lookup.json',
    'n8n/import/wf_overleaf_project_bridge.json',
    'n8n/import/wf_vscode_local_bridge.json',
    'n8n/import/wf_workflow_promotion_pipeline.json',
    'n8n/import/wf_workflow_version_history.json',
    'n8n/import/wf_workflow_version_rollback.json',
    'n8n/import/wf_retry_orchestrator_v2.json',
    'n8n/import/wf_queue_runtime_audit.json',
    'n8n/import/wf_workflow_execution_cap_guard.json',
    'n8n/import/wf_connector_failure_isolation_audit.json',
    'n8n/import/wf_ai_task_router.json',
    'n8n/import/wf_rag_document_ingest_governed.json',
    'n8n/import/wf_connector_health_monitor.json',
    'n8n/import/wf_admin_monitoring_dashboard.json',
    'n8n/import/wf_idempotency_guard.json',
    'n8n/import/wf_auth_guard.json',
    'n8n/import/wf_release_manifest_build.json',
    'n8n/import/wf_release_checksum_validate.json',
    'n8n/import/wf_release_rollback_package.json',
    'n8n/import/wf_release_preflight_validation.json',
    'n8n/import/wf_release_publish_pipeline.json',
    'n8n/import/wf_release_publication_audit.json',
    'n8n/import/wf_release_channel_upsert.json',
    'n8n/import/wf_release_channel_plan.json',
    'n8n/import/wf_release_channel_execute.json',
    'n8n/import/wf_release_channel_execution_audit.json',
    'scripts/smoke_test_connectors.py',
    'scripts/build_release_manifest.py',
    'scripts/validate_release_checksums.py',
    'scripts/build_release_rollback_package.py',
    'scripts/run_release_preflight.py',
    'scripts/build_release_publication_report.py',
    'scripts/build_release_channel_report.py',
    'scripts/build_release_channel_execution_report.py',
    'scripts/sync_connector_registry.py',
    'scripts/connector_preflight_report.py',
    'scripts/build_connector_workflow_manifest.py',
    'scripts/build_connector_readiness_report.py',
    'scripts/build_connector_deployment_plan.py',
    'scripts/build_connector_rollout_bundle.py',
    'scripts/build_connector_persistence_report.py',
    'scripts/build_connector_credential_matrix.py',
    'scripts/verify_connector_persistence.py',
    'scripts/check_queue_runtime.py',
    'scripts/check_workflow_execution_caps.py',
    'scripts/build_ai_control_report.py',
    'scripts/build_rag_governance_report.py',
    'service/app/tenant.py',
    'service/app/lifecycle.py',
    'docs/DATA_LIFECYCLE_GUIDE.md',
    'docs/generated_tenant_context_report.json',
    'docs/generated_tenant_enforcement_report.json',
    'migrations/015_tenant_enforcement_controls.sql',
    'n8n/import/wf_tenant_policy_upsert.json',
    'n8n/import/wf_tenant_enforcement_audit.json',
    'scripts/build_tenant_enforcement_report.py',
    'docs/generated_data_lifecycle_report.json',
    'docs/generated_data_lifecycle_cleanup.json',
    'migrations/013_data_lifecycle_controls.sql',
    'migrations/014_tenant_hardening.sql',
    'n8n/import/wf_data_lifecycle_audit.json',
    'n8n/import/wf_data_lifecycle_cleanup.json',
    'n8n/import/wf_tenant_membership_upsert.json',
    'n8n/import/wf_tenant_context_audit.json',
    'scripts/build_data_lifecycle_report.py',
    'scripts/run_data_lifecycle_cleanup.py',
    'docs/generated_tenant_row_isolation_report.json',
    'docs/generated_tenant_query_scope_report.json',
    'docs/generated_tenant_query_coverage_report.json',
    'migrations/017_tenant_row_isolation_controls.sql',
    'migrations/018_release_channel_automation.sql',
    'migrations/019_release_channel_execution_automation.sql',
    'n8n/import/wf_tenant_row_policy_upsert.json',
    'n8n/import/wf_tenant_row_isolation_audit.json',
    'scripts/build_tenant_row_isolation_report.py',
    'scripts/build_tenant_query_scope_report.py',
    'scripts/build_tenant_query_coverage_report.py',
    'n8n/import/wf_tenant_query_scope_audit.json',
    'n8n/import/wf_tenant_query_coverage_audit.json',
    'migrations/020_tenant_query_scope_controls.sql',
    'migrations/021_tenant_query_coverage_controls.sql',
    'service/app/tenant_row.py',
    'scripts/build_tenant_context_report.py',
]
missing = [p for p in required if not (root / p).exists()]
assert not missing, f'Missing required files: {missing}'

env_keys = {
    line.split('=', 1)[0]
    for line in (root / 'deploy' / '.env.example').read_text().splitlines()
    if line and not line.startswith('#') and '=' in line
}
legacy_placeholders = [
    'MLFLOW_BASE_URL',
    'FIGMA_TOKEN',
    'GOOGLE_DRIVE_BEARER_TOKEN',
    'OVERLEAF_BEARER_TOKEN',
    'NOTEBOOKLM_BEARER_TOKEN',
    'CANVAS_BEARER_TOKEN',
    'ANTIGRAVITY_BEARER_TOKEN',
    'VSCODE_BEARER_TOKEN',
    'VSCODE_BASE_URL',
    'MERMAID_BASE_URL',
    'AZURE_SUBSCRIPTION_ID',
    'AZURE_RESOURCE_GROUP',
]
combined_workflows = '\n'.join(path.read_text() for path in (root / 'n8n' / 'import').glob('wf_ext_*.json'))
assert not [item for item in legacy_placeholders if item in combined_workflows], 'legacy connector placeholders still present in wf_ext templates'

for svc in ['mlflow', 'azure_ml', 'drawio', 'figma', 'mermaid', 'canvas', 'kaggle', 'notebooklm', 'google_drive', 'overleaf', 'pubmed', 'arxiv', 'antigravity', 'vscode']:
    spec = json.loads((root / 'connectors' / 'specs' / f'{svc}.json').read_text())
    assert spec.get('implementation_status'), svc
    assert spec.get('integration_mode'), svc
    for key in [spec.get('base_url_env'), *spec.get('required_credentials', []), *spec.get('optional_credentials', [])]:
        if key:
            assert key in env_keys, f'{svc} missing env placeholder {key}'
print('package validation ok')
